"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const client_1 = require("@prisma/client");
const bcryptjs_1 = __importDefault(require("bcryptjs"));
const prisma = new client_1.PrismaClient();
async function main() {
    console.log('🌱 Starting QuickStore database seed...');
    console.log('⚙️ Seeding Store Settings...');
    await prisma.storeSetting.upsert({
        where: { id: 'default-store-setting' },
        update: {},
        create: {
            id: 'default-store-setting',
            storeName: 'QuickStore',
            storeLogo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=400&q=80',
            storePhone: '+91 98765 43210',
            storeEmail: 'support@quickstore.in',
            storeAddress: 'Shop 4, Green Avenue, 100ft Road, Indiranagar, Bengaluru, Karnataka 560038',
            storeLatitude: 12.9716,
            storeLongitude: 77.5946,
            maxDeliveryRadiusKm: 7.5,
            minOrderAmount: 99,
            deliveryFee: 25,
            freeDeliveryThreshold: 299,
            codEnabled: true,
            maxCodAmount: 2000,
            onlinePaymentEnabled: true,
            isOpen: true,
            openingTime: '06:00',
            closingTime: '23:00',
            estimatedDeliveryMinutes: 15,
            taxPercentage: 5.0,
        },
    });
    console.log('👤 Seeding Admin and Demo Customer Accounts...');
    const adminPasswordHash = await bcryptjs_1.default.hash('Admin@123456', 10);
    const customerPasswordHash = await bcryptjs_1.default.hash('Customer@123456', 10);
    const adminUser = await prisma.user.upsert({
        where: { email: 'admin@quickstore.com' },
        update: { passwordHash: adminPasswordHash, role: 'ADMIN' },
        create: {
            name: 'Store Manager (Admin)',
            email: 'admin@quickstore.com',
            phone: '9999900000',
            passwordHash: adminPasswordHash,
            role: 'ADMIN',
            profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
        },
    });
    const customerUser = await prisma.user.upsert({
        where: { email: 'customer@example.com' },
        update: { passwordHash: customerPasswordHash },
        create: {
            name: 'Aarav Sharma',
            email: 'customer@example.com',
            phone: '9876501234',
            passwordHash: customerPasswordHash,
            role: 'CUSTOMER',
            profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=256&q=80',
        },
    });
    await prisma.cart.upsert({
        where: { userId: customerUser.id },
        update: {},
        create: { userId: customerUser.id },
    });
    await prisma.address.deleteMany({ where: { userId: customerUser.id } });
    await prisma.address.create({
        data: {
            userId: customerUser.id,
            fullName: 'Aarav Sharma',
            phone: '9876501234',
            house: 'Flat 402, Sunshine Heights',
            street: '12th Main Road, HAL 2nd Stage',
            area: 'Indiranagar',
            city: 'Bengaluru',
            state: 'Karnataka',
            pincode: '560038',
            landmark: 'Near Metro Station Pillar 124',
            latitude: 12.9784,
            longitude: 77.6408,
            addressType: 'HOME',
            isDefault: true,
        },
    });
    console.log('🎟️ Seeding Promotional Coupons...');
    const coupons = [
        {
            code: 'WELCOME50',
            discountType: 'PERCENTAGE',
            discountValue: 50,
            minimumOrderAmount: 199,
            maximumDiscount: 100,
            startDate: new Date('2025-01-01'),
            expiryDate: new Date('2028-12-31'),
            usageLimit: 1000,
            perCustomerLimit: 1,
            isActive: true,
        },
        {
            code: 'QUICK100',
            discountType: 'FIXED',
            discountValue: 100,
            minimumOrderAmount: 499,
            maximumDiscount: null,
            startDate: new Date('2025-01-01'),
            expiryDate: new Date('2028-12-31'),
            usageLimit: 500,
            perCustomerLimit: 2,
            isActive: true,
        },
        {
            code: 'SUPER20',
            discountType: 'PERCENTAGE',
            discountValue: 20,
            minimumOrderAmount: 299,
            maximumDiscount: 150,
            startDate: new Date('2025-01-01'),
            expiryDate: new Date('2028-12-31'),
            usageLimit: 2000,
            perCustomerLimit: 3,
            isActive: true,
        },
    ];
    for (const c of coupons) {
        await prisma.coupon.upsert({
            where: { code: c.code },
            update: c,
            create: c,
        });
    }
    console.log('📦 Seeding Categories and Products...');
    const categoryData = [
        {
            name: 'Fruits & Vegetables',
            slug: 'fruits-vegetables',
            description: 'Fresh farm fruits and crisp organic vegetables harvested daily.',
            image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80',
            displayOrder: 1,
            products: [
                {
                    name: 'Fresh Farm Potatoes (Aloo)',
                    slug: 'fresh-farm-potatoes-1kg',
                    brand: 'Farm Fresh',
                    description: 'Premium quality golden farm potatoes, naturally grown and carefully sorted.',
                    price: 34,
                    mrp: 45,
                    unit: '1 kg',
                    stockQuantity: 45,
                    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Red Hybrid Onions (Pyaz)',
                    slug: 'red-hybrid-onions-1kg',
                    brand: 'Farm Fresh',
                    description: 'Pungent, flavorful and crisp red onions direct from the fields of Nashik.',
                    price: 42,
                    mrp: 55,
                    unit: '1 kg',
                    stockQuantity: 50,
                    image: 'https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Country Tomatoes (Tamatar)',
                    slug: 'country-tomatoes-500g',
                    brand: 'Farm Fresh',
                    description: 'Juicy, ripe and tangy country tomatoes, perfect for gravies and fresh salads.',
                    price: 26,
                    mrp: 35,
                    unit: '500 g',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Fresh Coriander Bunch (Dhaniya)',
                    slug: 'fresh-coriander-bunch',
                    brand: 'Hydroponic Greens',
                    description: 'Aromatic, hand-picked fresh green coriander leaves.',
                    price: 15,
                    mrp: 20,
                    unit: '100 g',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
                {
                    name: 'Robusta Bananas',
                    slug: 'robusta-bananas-6pcs',
                    brand: 'Fresh Orchard',
                    description: 'Naturally ripened sweet robusta bananas rich in potassium and energy.',
                    price: 39,
                    mrp: 48,
                    unit: '6 pcs',
                    stockQuantity: 35,
                    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Royal Gala Red Apples',
                    slug: 'royal-gala-red-apples-4pcs',
                    brand: 'Shimla Fresh',
                    description: 'Sweet, crisp and aromatic imported Royal Gala red apples.',
                    price: 145,
                    mrp: 180,
                    unit: '4 pcs (approx 600g)',
                    stockQuantity: 25,
                    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
            ],
        },
        {
            name: 'Dairy, Bread & Eggs',
            slug: 'dairy-bread-eggs',
            description: 'Pasteurized milk, farm eggs, artisan breads, paneer, and butter.',
            image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
            displayOrder: 2,
            products: [
                {
                    name: 'Amul Taaza Homogenised Toned Milk',
                    slug: 'amul-taaza-toned-milk-1l',
                    brand: 'Amul',
                    description: 'Pure, fresh, and nutritious toned milk. 3.0% fat and 8.5% SNF.',
                    price: 54,
                    mrp: 56,
                    unit: '1 L',
                    stockQuantity: 60,
                    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Amul Salted Butter',
                    slug: 'amul-salted-butter-100g',
                    brand: 'Amul',
                    description: 'Delicious utterly butterly Amul salted butter made from fresh cream.',
                    price: 58,
                    mrp: 60,
                    unit: '100 g',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Fresh Malai Paneer Block',
                    slug: 'fresh-malai-paneer-200g',
                    brand: 'MilkyMist',
                    description: 'Soft, creamy and protein-rich fresh cottage cheese for curries.',
                    price: 89,
                    mrp: 105,
                    unit: '200 g',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Farm Fresh White Table Eggs',
                    slug: 'farm-fresh-white-eggs-6pcs',
                    brand: 'Eggoz',
                    description: 'Cleaned, sanitized and hormone-free protein-rich farm eggs.',
                    price: 52,
                    mrp: 65,
                    unit: '6 pcs',
                    stockQuantity: 50,
                    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Modern 100% Whole Wheat Bread',
                    slug: 'modern-whole-wheat-bread-400g',
                    brand: 'Modern',
                    description: 'Healthy and fiber-rich 100% whole wheat sliced bread.',
                    price: 45,
                    mrp: 50,
                    unit: '400 g',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
                {
                    name: 'Epigamia Greek Yogurt (Wild Blueberry)',
                    slug: 'epigamia-greek-yogurt-blueberry-90g',
                    brand: 'Epigamia',
                    description: 'High-protein Greek yogurt with real wild blueberry fruit puree.',
                    price: 50,
                    mrp: 60,
                    unit: '90 g',
                    stockQuantity: 20,
                    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Snacks & Munchies',
            slug: 'snacks-munchies',
            description: 'Crisps, chips, roasted nuts, popcorn, and traditional Indian namkeen.',
            image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
            displayOrder: 3,
            products: [
                {
                    name: "Lay's India's Magic Masala Potato Chips",
                    slug: 'lays-magic-masala-chips-50g',
                    brand: "Lay's",
                    description: 'Classic crinkle cut potato chips with an explosion of hot spicy Indian spices.',
                    price: 20,
                    mrp: 20,
                    unit: '50 g',
                    stockQuantity: 80,
                    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Kurkure Masala Munch Crispy Snack',
                    slug: 'kurkure-masala-munch-85g',
                    brand: 'Kurkure',
                    description: 'Crunchy tedhe-medhe savory puffs with a spicy masala seasoning.',
                    price: 20,
                    mrp: 20,
                    unit: '85 g',
                    stockQuantity: 70,
                    image: 'https://images.unsplash.com/photo-1621447504864-d8686e12698c?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Haldiram Aloo Bhujia Crispy Sev',
                    slug: 'haldiram-aloo-bhujia-200g',
                    brand: 'Haldiram',
                    description: 'Spicy mint-infused potato and gram flour crispy noodle namkeen.',
                    price: 48,
                    mrp: 55,
                    unit: '200 g',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
                {
                    name: 'Act II Golden Sizzle Butter Popcorn',
                    slug: 'act-ii-butter-popcorn-70g',
                    brand: 'Act II',
                    description: 'Hot, fresh, buttery instant microwave popcorn ready in 3 minutes.',
                    price: 35,
                    mrp: 40,
                    unit: '70 g',
                    stockQuantity: 45,
                    image: 'https://images.unsplash.com/photo-1578849278619-e73505e9610f?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
                {
                    name: 'Doritos Cheese Supreme Nachos',
                    slug: 'doritos-cheese-supreme-nachos-60g',
                    brand: 'Doritos',
                    description: 'Crunchy triangular corn chips loaded with rich cheesy flavor.',
                    price: 30,
                    mrp: 30,
                    unit: '60 g',
                    stockQuantity: 50,
                    image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Cold Drinks & Juices',
            slug: 'cold-drinks-juices',
            description: 'Chilled sodas, 100% pure fruit juices, iced tea, energy drinks, and coconut water.',
            image: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=400&q=80',
            displayOrder: 4,
            products: [
                {
                    name: 'Coca-Cola Original Carbonated Drink',
                    slug: 'coca-cola-can-300ml',
                    brand: 'Coca-Cola',
                    description: 'Chilled refreshing classic Coca-Cola in a convenient sleek can.',
                    price: 40,
                    mrp: 40,
                    unit: '300 ml',
                    stockQuantity: 65,
                    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Tropicana 100% Real Orange Juice',
                    slug: 'tropicana-orange-juice-1l',
                    brand: 'Tropicana',
                    description: 'No added sugar, pure refreshing orange juice squeezed from real oranges.',
                    price: 119,
                    mrp: 140,
                    unit: '1 L',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Red Bull Energy Drink',
                    slug: 'red-bull-energy-drink-250ml',
                    brand: 'Red Bull',
                    description: 'Vitalizes body and mind with caffeine, taurine, B-group vitamins, and sugars.',
                    price: 125,
                    mrp: 125,
                    unit: '250 ml',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
                {
                    name: 'Raw Pressery Tender Coconut Water',
                    slug: 'raw-pressery-coconut-water-200ml',
                    brand: 'Raw Pressery',
                    description: '100% natural, refreshing and hydrating tender coconut water.',
                    price: 55,
                    mrp: 60,
                    unit: '200 ml',
                    stockQuantity: 35,
                    image: 'https://images.unsplash.com/photo-1544253103-6d0eb0f6e919?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
            ],
        },
        {
            name: 'Instant & Frozen Foods',
            slug: 'instant-frozen-foods',
            description: 'Noodles, instant pasta, frozen fries, veg nuggets, and ready-to-eat meals.',
            image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80',
            displayOrder: 5,
            products: [
                {
                    name: 'Maggi 2-Minute Masala Instant Noodles (Pack of 4)',
                    slug: 'maggi-masala-noodles-4pack',
                    brand: 'Nestle',
                    description: "India's most loved 2-minute instant noodles with the authentic masala tastemaker.",
                    price: 56,
                    mrp: 58,
                    unit: '280 g (4x70g)',
                    stockQuantity: 75,
                    image: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'McCain French Fries Crispy Crunchy',
                    slug: 'mccain-french-fries-420g',
                    brand: 'McCain',
                    description: 'Golden, crispy restaurant-style potato french fries ready to fry or bake.',
                    price: 110,
                    mrp: 130,
                    unit: '420 g',
                    stockQuantity: 25,
                    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Samyang Hot Buldak Spicy 2x Noodles',
                    slug: 'samyang-buldak-2x-spicy-noodles-140g',
                    brand: 'Samyang',
                    description: 'Fiery hot Korean stir-fried ramen noodles with extreme spice kick.',
                    price: 135,
                    mrp: 160,
                    unit: '140 g',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Tea, Coffee & Health Drinks',
            slug: 'tea-coffee-health-drinks',
            description: 'Chai leaves, instant coffee, filter coffee, green tea, and health malt powders.',
            image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=400&q=80',
            displayOrder: 6,
            products: [
                {
                    name: 'Tata Tea Gold Premium Black Tea',
                    slug: 'tata-tea-gold-500g',
                    brand: 'Tata Tea',
                    description: 'A rich blend of Assam CTC teas with gently rolled long leaves for superior aroma.',
                    price: 275,
                    mrp: 310,
                    unit: '500 g',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Nescafe Classic 100% Pure Instant Coffee',
                    slug: 'nescafe-classic-coffee-jar-100g',
                    brand: 'Nescafe',
                    description: 'Signature rich aroma and full-bodied taste made from slow-roasted Robusta beans.',
                    price: 220,
                    mrp: 245,
                    unit: '100 g Jar',
                    stockQuantity: 35,
                    image: 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Tetley Pure Green Tea (25 Tea Bags)',
                    slug: 'tetley-green-tea-25bags',
                    brand: 'Tetley',
                    description: 'Rich in natural antioxidants to boost metabolism and promote wellness.',
                    price: 135,
                    mrp: 160,
                    unit: '25 Tea Bags',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1627435601361-ec25f5b1d0e5?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Atta, Rice & Dals',
            slug: 'atta-rice-dals',
            description: 'Stone ground wheat atta, aged basmati rice, toor dal, moong dal, and whole grains.',
            image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
            displayOrder: 7,
            products: [
                {
                    name: 'Aashirvaad Shudh Chakki Whole Wheat Atta',
                    slug: 'aashirvaad-chakki-atta-5kg',
                    brand: 'Aashirvaad',
                    description: '100% whole wheat grain flour stone-ground to perfection for soft, fluffy rotis.',
                    price: 245,
                    mrp: 275,
                    unit: '5 kg',
                    stockQuantity: 50,
                    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'India Gate Feast Rozzana Basmati Rice',
                    slug: 'india-gate-basmati-rice-1kg',
                    brand: 'India Gate',
                    description: 'Long grain, aromatic basmati rice aged to perfection for daily meals.',
                    price: 105,
                    mrp: 130,
                    unit: '1 kg',
                    stockQuantity: 45,
                    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Tata Sampann Unpolished Toor Dal',
                    slug: 'tata-sampann-toor-dal-1kg',
                    brand: 'Tata Sampann',
                    description: 'Unpolished arhar/toor dal rich in natural dietary protein and wholesome nutrients.',
                    price: 168,
                    mrp: 195,
                    unit: '1 kg',
                    stockQuantity: 35,
                    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
            ],
        },
        {
            name: 'Cleaning & Household',
            slug: 'cleaning-household',
            description: 'Detergents, floor cleaners, dishwashing bars, garbage bags, and bathroom cleaners.',
            image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=400&q=80',
            displayOrder: 8,
            products: [
                {
                    name: 'Surf Excel Matic Top Load Liquid Detergent',
                    slug: 'surf-excel-matic-liquid-1l',
                    brand: 'Surf Excel',
                    description: 'Superior stain removal in washing machines without leaving white residue.',
                    price: 215,
                    mrp: 240,
                    unit: '1 L',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Vim Lemon Dishwash Gel with Power of 100 Lemons',
                    slug: 'vim-dishwash-gel-500ml',
                    brand: 'Vim',
                    description: 'Cleans tough grease from utensils easily without scratching.',
                    price: 99,
                    mrp: 120,
                    unit: '500 ml',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Lizol Floral Disinfectant Surface Cleaner',
                    slug: 'lizol-floral-cleaner-500ml',
                    brand: 'Lizol',
                    description: 'Kills 99.9% of germs and leaves a refreshing floral fragrance on floors.',
                    price: 98,
                    mrp: 110,
                    unit: '500 ml',
                    stockQuantity: 35,
                    image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Personal Care & Hygiene',
            slug: 'personal-care-hygiene',
            description: 'Body soaps, shampoos, toothpastes, deodorants, face wash, and skin creams.',
            image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=400&q=80',
            displayOrder: 9,
            products: [
                {
                    name: 'Dettol Original Germ Protection Bathing Soap (Pack of 3)',
                    slug: 'dettol-soap-pack-of-3',
                    brand: 'Dettol',
                    description: 'Trusted antibacterial soap with pine fragrance for 100% germ protection.',
                    price: 135,
                    mrp: 150,
                    unit: '3x125 g',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1607006314352-701a2f64d008?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Colgate Total All-in-One Toothpaste',
                    slug: 'colgate-total-toothpaste-150g',
                    brand: 'Colgate',
                    description: '12-hour antibacterial whole mouth protection against cavities and plaque.',
                    price: 115,
                    mrp: 135,
                    unit: '150 g',
                    stockQuantity: 50,
                    image: 'https://images.unsplash.com/photo-1559599101-f09722fb4948?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
                {
                    name: 'Head & Shoulders Cool Menthol Anti-Dandruff Shampoo',
                    slug: 'head-and-shoulders-cool-menthol-180ml',
                    brand: 'Head & Shoulders',
                    description: 'Invigorating menthol formula leaves scalp dandruff-free and fresh.',
                    price: 175,
                    mrp: 199,
                    unit: '180 ml',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Chocolates & Sweets',
            slug: 'chocolates-sweets',
            description: 'Milk chocolates, dark chocolates, gourmet wafers, and traditional Indian sweets.',
            image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?auto=format&fit=crop&w=400&q=80',
            displayOrder: 10,
            products: [
                {
                    name: 'Cadbury Dairy Milk Silk Chocolate Bar',
                    slug: 'cadbury-dairy-milk-silk-60g',
                    brand: 'Cadbury',
                    description: 'Smooth, creamy, and velvety melt-in-mouth milk chocolate bar.',
                    price: 80,
                    mrp: 85,
                    unit: '60 g',
                    stockQuantity: 70,
                    image: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Ferrero Rocher Hazelnut Chocolates (Pack of 4)',
                    slug: 'ferrero-rocher-4pcs',
                    brand: 'Ferrero',
                    description: 'Crispy wafer shell filled with creamy chocolate and a whole roasted hazelnut.',
                    price: 145,
                    mrp: 160,
                    unit: '50 g (4 pcs)',
                    stockQuantity: 30,
                    image: 'https://images.unsplash.com/photo-1548848221-0c2e497ed557?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Haldiram Gulab Jamun Tin Can',
                    slug: 'haldiram-gulab-jamun-500g',
                    brand: 'Haldiram',
                    description: 'Soft and spongy cottage cheese dumplings soaked in aromatic cardamom sugar syrup.',
                    price: 125,
                    mrp: 140,
                    unit: '500 g',
                    stockQuantity: 25,
                    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Baby Care & Diapers',
            slug: 'baby-care-diapers',
            description: 'Pants diapers, wet wipes, baby lotions, baby wash, and feeding bottles.',
            image: 'https://images.unsplash.com/photo-1519689680058-324335c77eda?auto=format&fit=crop&w=400&q=80',
            displayOrder: 11,
            products: [
                {
                    name: 'Pampers All Round Protection Pants Diaper (Size M)',
                    slug: 'pampers-all-round-protection-m-32pcs',
                    brand: 'Pampers',
                    description: 'Magic gel technology provides up to 12 hours of absorption and dryness.',
                    price: 499,
                    mrp: 599,
                    unit: 'Pack of 32',
                    stockQuantity: 25,
                    image: 'https://images.unsplash.com/photo-1519689680058-324335c77eda?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Himalaya Gentle Baby Wipes with Aloe Vera',
                    slug: 'himalaya-gentle-baby-wipes-72wipes',
                    brand: 'Himalaya',
                    description: 'Infused with goodness of Aloe Vera and Indian Lotus for gentle soothing skin care.',
                    price: 145,
                    mrp: 175,
                    unit: 'Pack of 72 Wipes',
                    stockQuantity: 35,
                    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=400&q=80',
                    isFeatured: false,
                },
            ],
        },
        {
            name: 'Bakery & Biscuits',
            slug: 'bakery-biscuits',
            description: 'Bourbon, Marie Gold, Good Day cookies, tea rusks, burger buns, and pav.',
            image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
            displayOrder: 12,
            products: [
                {
                    name: 'Britannia Good Day Butter Cookies',
                    slug: 'britannia-good-day-butter-200g',
                    brand: 'Britannia',
                    description: 'Rich, buttery and crunchy cookies with signature smile cuts.',
                    price: 35,
                    mrp: 40,
                    unit: '200 g',
                    stockQuantity: 50,
                    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
                {
                    name: 'Freshly Baked Pav Buns (Pack of 6)',
                    slug: 'fresh-baked-pav-buns-6pcs',
                    brand: 'Bakers Corner',
                    description: 'Pillow soft bakery-fresh pav buns, ideal for vada pav and pav bhaji.',
                    price: 30,
                    mrp: 35,
                    unit: '6 pcs',
                    stockQuantity: 40,
                    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
                    isFeatured: true,
                },
            ],
        },
    ];
    for (const cat of categoryData) {
        const { products, ...catInfo } = cat;
        const category = await prisma.category.upsert({
            where: { slug: catInfo.slug },
            update: catInfo,
            create: catInfo,
        });
        for (const prod of products) {
            const discount = prod.mrp > prod.price ? Math.round(((prod.mrp - prod.price) / prod.mrp) * 100) : 0;
            await prisma.product.upsert({
                where: { slug: prod.slug },
                update: {
                    ...prod,
                    discount,
                    categoryId: category.id,
                },
                create: {
                    ...prod,
                    discount,
                    categoryId: category.id,
                },
            });
        }
    }
    console.log('✅ Seeding completed successfully!');
    console.log(`🔑 Admin Credentials: ${adminUser.email} / Admin@123456`);
    console.log(`🔑 Customer Credentials: ${customerUser.email} / Customer@123456`);
}
main()
    .catch((e) => {
    console.error('❌ Seeding failed:', e);
    process.exit(1);
})
    .finally(async () => {
    await prisma.$disconnect();
});
